version: "3.9"

services:
  streamlit-app:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    env_file: ./streamlit-app/.env
    ports:
      - ${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}
    restart: always
